spring:
  config:
    import: optional:file:.env[.properties]
  # MySQL 연결 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create # 개발 시 한정
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.batch_size: 50 # 엑셀 입력시 50개씩 묶어서 넣기
        order_inserts: true

  # Redis 연결 설정
  data:
    redis:
      host: localhost
      port: 6380

# JWT 커스텀 설정
jwt:
  secret: ${JWT_SECRET}
  access_expiration_time: ${JWT_ACCESS_EXPIRATION}
  refresh_expiration_time: ${JWT_REFRESH_EXPIRATION}
