-- 운영(prod) 전용 baseline: 운영 public 스키마 전체를 Flyway가 소유한다.
-- 생성 방식: 현재 엔티티로 ddl-auto:create 기동 후 pg_dump --schema-only 캡처(Hibernate DDL 원본).
--   → 같은 Hibernate 설정의 ddl-auto:validate 가 이 스키마에 대해 통과함이 구성상 보장된다.
-- dev/test는 이 위치(db/prod-migration)를 로드하지 않으므로 ddl-auto:create 와 충돌하지 않는다.
-- 대용량 텍스트(consultations.content/next_plan, feedbacks.content)는 TEXT 로 매핑(@Lob→oid 함정 제거).
-- 갱신 절차: 엔티티 변경 시 신규 Vx 마이그레이션을 db/prod-migration 에 추가(이 파일 수정 금지 — Flyway 체크섬).

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- (pg_dump 의 'CREATE SCHEMA public;' 제거 — public 스키마는 항상 존재하므로 충돌)


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: academic_calendars; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.academic_calendars (
    date date NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    day_type character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    CONSTRAINT academic_calendars_day_type_check CHECK (((day_type)::text = ANY ((ARRAY['WEEKDAY'::character varying, 'HOLIDAY'::character varying, 'VACATION'::character varying, 'EVENT'::character varying])::text[])))
);


--
-- Name: academic_calendars_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.academic_calendars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_calendars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assignments (
    classroom_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    due_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    subject_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    title character varying(200) NOT NULL,
    description text
);


--
-- Name: assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendances (
    date date NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    reason character varying(255),
    CONSTRAINT attendances_status_check CHECK (((status)::text = ANY ((ARRAY['PRESENT'::character varying, 'ABSENT'::character varying, 'LATE'::character varying, 'EARLY_LEAVE'::character varying])::text[])))
);


--
-- Name: attendances_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: classrooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classrooms (
    academic_year integer NOT NULL,
    class_num integer NOT NULL,
    grade integer NOT NULL,
    semester integer NOT NULL,
    created_at timestamp(6) without time zone,
    homeroom_teacher_id bigint,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: classrooms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.classrooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classrooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consultations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consultations (
    consultation_date timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    visibility character varying(20) NOT NULL,
    content text NOT NULL,
    next_plan text,
    CONSTRAINT consultations_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['RESTRICTED'::character varying, 'ALL_TEACHERS'::character varying])::text[])))
);


--
-- Name: consultations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.consultations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consultations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exams (
    academic_year integer NOT NULL,
    exam_date date,
    max_score integer NOT NULL,
    published boolean NOT NULL,
    semester integer NOT NULL,
    weight double precision NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    exam_type character varying(20) NOT NULL,
    name character varying(50) NOT NULL,
    coverage character varying(500),
    CONSTRAINT exams_exam_type_check CHECK (((exam_type)::text = ANY ((ARRAY['MIDTERM'::character varying, 'FINAL'::character varying])::text[])))
);


--
-- Name: exams_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedbacks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedbacks (
    is_public boolean NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    category character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    content text NOT NULL,
    CONSTRAINT feedbacks_category_check CHECK (((category)::text = ANY ((ARRAY['GRADE'::character varying, 'BEHAVIOR'::character varying, 'ATTENDANCE'::character varying, 'ATTITUDE'::character varying, 'ETC'::character varying])::text[]))),
    CONSTRAINT feedbacks_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])))
);


--
-- Name: feedbacks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feedbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedbacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grade_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grade_histories (
    after_score integer,
    before_score integer,
    changed_at timestamp(6) without time zone NOT NULL,
    changed_by_user_id bigint NOT NULL,
    id bigint NOT NULL,
    student_grade_id bigint NOT NULL,
    changed_by_name character varying(50) NOT NULL,
    reason character varying(200)
);


--
-- Name: grade_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grade_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grade_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grade_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grade_policies (
    a_min_score double precision NOT NULL,
    active boolean NOT NULL,
    b_min_score double precision NOT NULL,
    c_min_score double precision NOT NULL,
    d_min_score double precision NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    name character varying(100) NOT NULL
);


--
-- Name: grade_policies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grade_policies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grade_policies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    read_at timestamp(6) without time zone,
    recipient_user_id bigint NOT NULL,
    reference_id bigint,
    updated_at timestamp(6) without time zone,
    status character varying(10) NOT NULL,
    type character varying(30) NOT NULL,
    title character varying(100) NOT NULL,
    content character varying(500) NOT NULL,
    link_url character varying(500),
    CONSTRAINT notifications_status_check CHECK (((status)::text = ANY ((ARRAY['UNREAD'::character varying, 'READ'::character varying])::text[]))),
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['GRADE_PUBLISHED'::character varying, 'FEEDBACK_PUBLISHED'::character varying, 'ASSIGNMENT_CREATED'::character varying])::text[])))
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parent_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parent_invitations (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    relation_type character varying(20) NOT NULL,
    phone_number character varying(255) NOT NULL,
    CONSTRAINT parent_invitations_relation_type_check CHECK (((relation_type)::text = ANY ((ARRAY['FATHER'::character varying, 'MOTHER'::character varying])::text[])))
);


--
-- Name: parent_invitations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parent_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parent_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parent_student_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parent_student_mapping (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    parent_id bigint NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: parent_student_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parent_student_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parent_student_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parents (
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    relation_type character varying(20) NOT NULL,
    phone_number character varying(255) NOT NULL,
    CONSTRAINT parents_relation_type_check CHECK (((relation_type)::text = ANY ((ARRAY['FATHER'::character varying, 'MOTHER'::character varying])::text[])))
);


--
-- Name: semester_closures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.semester_closures (
    academic_year integer NOT NULL,
    filled_count integer NOT NULL,
    semester integer NOT NULL,
    closed_at timestamp(6) without time zone NOT NULL,
    closed_by_user_id bigint,
    id bigint NOT NULL,
    method character varying(20) NOT NULL,
    closed_by_name character varying(50) NOT NULL,
    reason character varying(200),
    CONSTRAINT semester_closures_method_check CHECK (((method)::text = ANY ((ARRAY['MANUAL'::character varying, 'AUTO_FALLBACK'::character varying])::text[])))
);


--
-- Name: semester_closures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.semester_closures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.semester_closures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_affiliations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_affiliations (
    student_num integer NOT NULL,
    classroom_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: student_affiliations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_affiliations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_affiliations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_grades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_grades (
    raw_score integer,
    created_at timestamp(6) without time zone,
    exam_id bigint NOT NULL,
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    attendance_status character varying(10) NOT NULL,
    version bigint,
    CONSTRAINT student_grades_attendance_status_check CHECK (((attendance_status)::text = ANY ((ARRAY['PRESENT'::character varying, 'ABSENT'::character varying, 'CHEATED'::character varying, 'NOT_SUBMITTED'::character varying])::text[])))
);


--
-- Name: student_grades_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_grades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_grades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_records (
    academic_year integer NOT NULL,
    semester integer NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    subject_id bigint,
    teacher_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    version bigint,
    content text NOT NULL,
    record_category character varying(255) NOT NULL,
    CONSTRAINT student_records_record_category_check CHECK (((record_category)::text = ANY ((ARRAY['SUBJECT_OPINION'::character varying, 'BEHAVIOR_OPINION'::character varying])::text[])))
);


--
-- Name: student_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_semester_stats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_semester_stats (
    academic_year integer NOT NULL,
    average_score double precision NOT NULL,
    grade_level character(1) NOT NULL,
    semester integer NOT NULL,
    total_score double precision NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT student_semester_stats_grade_level_check CHECK ((grade_level = ANY (ARRAY['A'::bpchar, 'B'::bpchar, 'C'::bpchar, 'D'::bpchar, 'E'::bpchar])))
);


--
-- Name: student_semester_stats_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_semester_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_semester_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
    enrollment_year integer NOT NULL,
    created_at timestamp(6) without time zone,
    homeroom_teacher_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    profile_image_key character varying(500),
    address character varying(1024),
    phone_number character varying(255)
);


--
-- Name: subject_assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subject_assignments (
    academic_year integer NOT NULL,
    semester integer NOT NULL,
    classroom_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    subject_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: subject_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subject_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subject_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subjects (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    name character varying(50) NOT NULL
);


--
-- Name: subjects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.submissions (
    assignment_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    submitted_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    content text,
    score integer,
    feedback text,
    CONSTRAINT submissions_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_SUBMITTED'::character varying, 'SUBMITTED'::character varying, 'LATE'::character varying])::text[])))
);


--
-- Name: submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teachers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teachers (
    created_at timestamp(6) without time zone,
    subject_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    employment_status character varying(20) NOT NULL,
    office_location character varying(50) NOT NULL,
    profile_image_key character varying(500),
    employee_number character varying(255) NOT NULL,
    office_phone_number character varying(255) NOT NULL,
    CONSTRAINT teachers_employment_status_check CHECK (((employment_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ON_LEAVE'::character varying, 'TRANSFERRED'::character varying, 'RETIRED'::character varying])::text[])))
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    gender character varying(50) NOT NULL,
    login_id character varying(50),
    name character varying(50) NOT NULL,
    role character varying(50) NOT NULL,
    status character varying(50) NOT NULL,
    password character varying(255),
    CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'TEACHER'::character varying, 'STUDENT'::character varying, 'PARENT'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: academic_calendars academic_calendars_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_calendars
    ADD CONSTRAINT academic_calendars_date_key UNIQUE (date);


--
-- Name: academic_calendars academic_calendars_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_calendars
    ADD CONSTRAINT academic_calendars_pkey PRIMARY KEY (id);


--
-- Name: assignments assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_pkey PRIMARY KEY (id);


--
-- Name: attendances attendances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendances
    ADD CONSTRAINT attendances_pkey PRIMARY KEY (id);


--
-- Name: classrooms classrooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classrooms
    ADD CONSTRAINT classrooms_pkey PRIMARY KEY (id);


--
-- Name: consultations consultations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultations
    ADD CONSTRAINT consultations_pkey PRIMARY KEY (id);


--
-- Name: exams exams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_pkey PRIMARY KEY (id);


--
-- Name: feedbacks feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT feedbacks_pkey PRIMARY KEY (id);


--
-- Name: grade_histories grade_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grade_histories
    ADD CONSTRAINT grade_histories_pkey PRIMARY KEY (id);


--
-- Name: grade_policies grade_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grade_policies
    ADD CONSTRAINT grade_policies_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: parent_invitations parent_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parent_invitations
    ADD CONSTRAINT parent_invitations_pkey PRIMARY KEY (id);


--
-- Name: parent_student_mapping parent_student_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parent_student_mapping
    ADD CONSTRAINT parent_student_mapping_pkey PRIMARY KEY (id);


--
-- Name: parents parents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parents
    ADD CONSTRAINT parents_pkey PRIMARY KEY (user_id);


--
-- Name: semester_closures semester_closures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.semester_closures
    ADD CONSTRAINT semester_closures_pkey PRIMARY KEY (id);


--
-- Name: student_affiliations student_affiliations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_affiliations
    ADD CONSTRAINT student_affiliations_pkey PRIMARY KEY (id);


--
-- Name: student_grades student_grades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_grades
    ADD CONSTRAINT student_grades_pkey PRIMARY KEY (id);


--
-- Name: student_records student_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_records
    ADD CONSTRAINT student_records_pkey PRIMARY KEY (id);


--
-- Name: student_semester_stats student_semester_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_semester_stats
    ADD CONSTRAINT student_semester_stats_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (user_id);


--
-- Name: subject_assignments subject_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_assignments
    ADD CONSTRAINT subject_assignments_pkey PRIMARY KEY (id);


--
-- Name: subjects subjects_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_name_key UNIQUE (name);


--
-- Name: subjects subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (id);


--
-- Name: submissions submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_pkey PRIMARY KEY (id);


--
-- Name: teachers teachers_employee_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_employee_number_key UNIQUE (employee_number);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (user_id);


--
-- Name: student_affiliations uk_affiliation_student_classroom; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_affiliations
    ADD CONSTRAINT uk_affiliation_student_classroom UNIQUE (student_id, classroom_id);


--
-- Name: classrooms uk_classroom_year_semester_grade_class; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classrooms
    ADD CONSTRAINT uk_classroom_year_semester_grade_class UNIQUE (academic_year, semester, grade, class_num);


--
-- Name: exams uk_exam_year_semester_type_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT uk_exam_year_semester_type_name UNIQUE (academic_year, semester, exam_type, name);


--
-- Name: student_grades uk_grade_student_exam_subject; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_grades
    ADD CONSTRAINT uk_grade_student_exam_subject UNIQUE (student_id, exam_id, subject_id);


--
-- Name: semester_closures uk_semester_closure_year_semester; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.semester_closures
    ADD CONSTRAINT uk_semester_closure_year_semester UNIQUE (academic_year, semester);


--
-- Name: student_semester_stats uk_stat_student_year_semester; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_semester_stats
    ADD CONSTRAINT uk_stat_student_year_semester UNIQUE (student_id, academic_year, semester);


--
-- Name: attendances uk_student_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendances
    ADD CONSTRAINT uk_student_date UNIQUE (student_id, date);


--
-- Name: student_records uk_student_record; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_records
    ADD CONSTRAINT uk_student_record UNIQUE (student_id, academic_year, semester, record_category, subject_id);


--
-- Name: subject_assignments uk_subject_assignment; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_assignments
    ADD CONSTRAINT uk_subject_assignment UNIQUE (teacher_id, classroom_id, subject_id, academic_year, semester);


--
-- Name: submissions uk_submission_assignment_student; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT uk_submission_assignment_student UNIQUE (assignment_id, student_id);


--
-- Name: users users_login_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_login_id_key UNIQUE (login_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_history_grade_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_history_grade_id ON public.grade_histories USING btree (student_grade_id, changed_at);


--
-- Name: idx_notification_recipient_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notification_recipient_status ON public.notifications USING btree (recipient_user_id, status);


--
-- Name: uk_behavior_record; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_behavior_record ON public.student_records USING btree (student_id, academic_year, semester, record_category) WHERE (subject_id IS NULL);


--
-- Name: student_records fk14kw1noyf35mj67hgg4hxriyi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_records
    ADD CONSTRAINT fk14kw1noyf35mj67hgg4hxriyi FOREIGN KEY (subject_id) REFERENCES public.subjects(id);


--
-- Name: grade_histories fk1rg985fc875rdnel4edtd4e6x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grade_histories
    ADD CONSTRAINT fk1rg985fc875rdnel4edtd4e6x FOREIGN KEY (student_grade_id) REFERENCES public.student_grades(id);


--
-- Name: student_grades fk2prq6208b200k5vwbupe5p5wx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_grades
    ADD CONSTRAINT fk2prq6208b200k5vwbupe5p5wx FOREIGN KEY (subject_id) REFERENCES public.subjects(id);


--
-- Name: consultations fk33s0quglpb7qauhr8b2cr9gwd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultations
    ADD CONSTRAINT fk33s0quglpb7qauhr8b2cr9gwd FOREIGN KEY (student_id) REFERENCES public.students(user_id);


--
-- Name: subject_assignments fk38waa73808sfqcmml0w7p7wx3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_assignments
    ADD CONSTRAINT fk38waa73808sfqcmml0w7p7wx3 FOREIGN KEY (classroom_id) REFERENCES public.classrooms(id);


--
-- Name: student_affiliations fk3966qv2x56ma2dc8vwolc5jms; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_affiliations
    ADD CONSTRAINT fk3966qv2x56ma2dc8vwolc5jms FOREIGN KEY (student_id) REFERENCES public.students(user_id);


--
-- Name: feedbacks fk4ocysx6ldsioryb4bx1etqw32; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT fk4ocysx6ldsioryb4bx1etqw32 FOREIGN KEY (student_id) REFERENCES public.students(user_id);


--
-- Name: attendances fk5uxbw3kpkq8nrljql5721i9lt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendances
    ADD CONSTRAINT fk5uxbw3kpkq8nrljql5721i9lt FOREIGN KEY (teacher_id) REFERENCES public.teachers(user_id);


--
-- Name: attendances fk7bm4q4wptspkenhrsjgatdmk0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendances
    ADD CONSTRAINT fk7bm4q4wptspkenhrsjgatdmk0 FOREIGN KEY (student_id) REFERENCES public.students(user_id);


--
-- Name: parent_student_mapping fk9crj08aadcmuvxrplu4oanboo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parent_student_mapping
    ADD CONSTRAINT fk9crj08aadcmuvxrplu4oanboo FOREIGN KEY (parent_id) REFERENCES public.parents(user_id);


--
-- Name: teachers fkb8dct7w2j1vl1r2bpstw5isc0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT fkb8dct7w2j1vl1r2bpstw5isc0 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: assignments fkbc73d2na4mq587q3y5nfuouli; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fkbc73d2na4mq587q3y5nfuouli FOREIGN KEY (classroom_id) REFERENCES public.classrooms(id);


--
-- Name: student_semester_stats fkc051st1q76ttbuyr97oqsx550; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_semester_stats
    ADD CONSTRAINT fkc051st1q76ttbuyr97oqsx550 FOREIGN KEY (student_id) REFERENCES public.students(user_id);


--
-- Name: classrooms fkcfatkwvf0rwvg18qa5o9erwx5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classrooms
    ADD CONSTRAINT fkcfatkwvf0rwvg18qa5o9erwx5 FOREIGN KEY (homeroom_teacher_id) REFERENCES public.teachers(user_id);


--
-- Name: parents fkchh8tf8w072tapgqoijrahojk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parents
    ADD CONSTRAINT fkchh8tf8w072tapgqoijrahojk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: student_affiliations fkd0w9fq0jslm7hbp6yyww3cfn5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_affiliations
    ADD CONSTRAINT fkd0w9fq0jslm7hbp6yyww3cfn5 FOREIGN KEY (classroom_id) REFERENCES public.classrooms(id);


--
-- Name: students fkdt1cjx5ve5bdabmuuf3ibrwaq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkdt1cjx5ve5bdabmuuf3ibrwaq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: parent_invitations fke3eioved3rgc51epnn9gy65cs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parent_invitations
    ADD CONSTRAINT fke3eioved3rgc51epnn9gy65cs FOREIGN KEY (student_id) REFERENCES public.students(user_id);


--
-- Name: student_grades fke8t3tau7ti61n06siogcuigkq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_grades
    ADD CONSTRAINT fke8t3tau7ti61n06siogcuigkq FOREIGN KEY (student_id) REFERENCES public.students(user_id);


--
-- Name: parent_student_mapping fkfggqmnisi5shd5a9o9kav35o4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parent_student_mapping
    ADD CONSTRAINT fkfggqmnisi5shd5a9o9kav35o4 FOREIGN KEY (student_id) REFERENCES public.students(user_id);


--
-- Name: student_grades fkh0c11iij2w9b0sihlxu6qb6eb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_grades
    ADD CONSTRAINT fkh0c11iij2w9b0sihlxu6qb6eb FOREIGN KEY (exam_id) REFERENCES public.exams(id);


--
-- Name: submissions fkhwebuw14r6lb2ja85w9mwa8vf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fkhwebuw14r6lb2ja85w9mwa8vf FOREIGN KEY (student_id) REFERENCES public.students(user_id);


--
-- Name: subject_assignments fkjqbn3pvhybwy6nd669qhxtsyx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_assignments
    ADD CONSTRAINT fkjqbn3pvhybwy6nd669qhxtsyx FOREIGN KEY (teacher_id) REFERENCES public.teachers(user_id);


--
-- Name: feedbacks fkkmb4xm2mu42sp99hn4o0v3knf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT fkkmb4xm2mu42sp99hn4o0v3knf FOREIGN KEY (teacher_id) REFERENCES public.teachers(user_id);


--
-- Name: student_records fkm59ttuv767w84vsy8jdd0suf6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_records
    ADD CONSTRAINT fkm59ttuv767w84vsy8jdd0suf6 FOREIGN KEY (student_id) REFERENCES public.students(user_id);


--
-- Name: consultations fkmcxt2xr631s310knbt0e5qu11; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultations
    ADD CONSTRAINT fkmcxt2xr631s310knbt0e5qu11 FOREIGN KEY (teacher_id) REFERENCES public.teachers(user_id);


--
-- Name: assignments fkmd9krpotkeiujbef6ren2yvq5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fkmd9krpotkeiujbef6ren2yvq5 FOREIGN KEY (subject_id) REFERENCES public.subjects(id);


--
-- Name: subject_assignments fkmx4q94rdji3g6c7ovjcyesgbb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_assignments
    ADD CONSTRAINT fkmx4q94rdji3g6c7ovjcyesgbb FOREIGN KEY (subject_id) REFERENCES public.subjects(id);


--
-- Name: student_records fko4x2b1wj2df4tdb59i9xr1bh9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_records
    ADD CONSTRAINT fko4x2b1wj2df4tdb59i9xr1bh9 FOREIGN KEY (teacher_id) REFERENCES public.teachers(user_id);


--
-- Name: students fkq836dcs0scpg9d2l2y4r8cc4d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkq836dcs0scpg9d2l2y4r8cc4d FOREIGN KEY (homeroom_teacher_id) REFERENCES public.teachers(user_id);


--
-- Name: submissions fkrirbb44savy2g7nws0hoxs949; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fkrirbb44savy2g7nws0hoxs949 FOREIGN KEY (assignment_id) REFERENCES public.assignments(id);


--
-- Name: teachers fksahkj7ew9hfs6byrpl75br5lx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT fksahkj7ew9hfs6byrpl75br5lx FOREIGN KEY (subject_id) REFERENCES public.subjects(id);


--
-- Name: assignments fkthsv5nybgtij6aybrhfb6n6of; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fkthsv5nybgtij6aybrhfb6n6of FOREIGN KEY (teacher_id) REFERENCES public.teachers(user_id);


--
-- PostgreSQL database dump complete
--


